spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chat_api
    username: root
    password: cinema
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    root: info
    org.hibernate.sql: INFO